### ISSUE TITLE
Cannot run Launcher.java when following Tutorial 1

### ISSUE THREAD

**Issue by Douglch** [nus-cs2103-AY2223S2/forum#122]
Intellij Version: 2022.3.1
Java version: 11.0.14.1
OS: Windows
Github branch: [branch-Level-10](https://github.com/Douglch/ip/tree/branch-Level-10)

I followed the instructions for tutorial 1 for JavaFX, adding the appropriate lines and imports to my main class accordingly as well as in the Launcher.java class created. However, I kept faced the issue below when I tried running Launcher.java for the final step of the tutorial. 
The execution below was ran with --stacktrace.

```> Task :Launcher.main() FAILED
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class lele.Lele
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodException: lele.Lele.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:801)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more

FAILURE: Build failed with an exception.
```

**Comment by SPWwj** [comment]
Create a default constructor for your lele.class. 

Just a suggestion that since you not using any code in lele.class you can create a separate class to handle gui and only call the lele when necessary.

You may look at my code for reference. ：）

**Comment by Douglch** [comment]
Damn bruh you the 🐐,  thank you :)
