### ISSUE TITLE
Unable to load images, `getResourceAsStream` returning null

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#171]
I'm trying to implement the [JavaFX tutorial part 3] but after implementing the images, I keep getting this error when running:

[JavaFX tutorial part 3]: https://se-education.org/guides/tutorials/javaFxPart3.html

```bash
$  cd c:\\Users\\shaun\\Desktop\\repositories\\ip ; /usr/bin/env C:\\Program\ Files\\Java\\jdk-11.0.14\\bin\\java.exe @C:\\Users\\shaun\\AppData\\Local\\Temp\\cp_ecd2bo7vr45zarn5s3muqg0w1.argfile duke.Launcher
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class duke.Duke
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 1 more
Caused by: java.lang.NullPointerException: Input stream must not be null
        at javafx.scene.image.Image.validateInputStream(Image.java:1117)
        at javafx.scene.image.Image.<init>(Image.java:701)
        at duke.Duke.<init>(Duke.java:33)
        ... 13 more
```

<br>

The offending line (ie. `Duke.java:33`) is this:

```java
31: ...
32: public class Duke extends Application {
33:     private Image user = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));
34:     private Image duke = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png"));
35:     ...
```

<br>

This is my folder structure, where the images is in `src/resources/images` as per the JavaFX tutorial:

![image](https://user-images.githubusercontent.com/35413456/218317102-b136410c-ebd6-4081-b434-7feae0143752.png)

<br>

_PS: don't mind the red highlighted files, its just the checkstyle acting up_

**Comment by Johnchiahk** [comment]
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

Did u add these imports in Main.java?

**Comment by damithc** [comment]
@EvitanRelta While waiting for inputs from others, you can push the code to a branch and share here so that other can try to replicate the problem.

**Comment by astraxq** [comment]
I came across this issue too in VSCode, I cleared the workspace cache and it worked as per normal perhaps this can help.

**Comment by arkarsg** [comment]
If you are using VSCode, try running through Gradle.

I face Exceptions when I run through `Launcher.java` but works through `run` in Gradle.

**Comment by jugsliao** [comment]
Not sure if this helps but sometimes my errors disappear when I close and open intelliJ and run the launcher again.

**Comment by JavonTeo** [comment]
If it still doesn't work, perhaps you could try editing the filepath

**Comment by EvitanRelta** [comment]
> import javafx.scene.image.Image; import javafx.scene.image.ImageView;
> 
> Did u add these imports in Main.java?

yup i did

**Comment by damithc** [comment]
> @EvitanRelta While waiting for inputs from others, you can push the code to a branch and share here so that other can try to replicate the problem.

If the problem is still not resolved, I suggest the above.

**Comment by EvitanRelta** [comment]
> @EvitanRelta While waiting for inputs from others, you can push the code to a branch and share here so that other can try to replicate the problem.

Alright, i've pushed it to [my repo]'s master branch.

[my repo]: https://github.com/EvitanRelta/ip

**Comment by EvitanRelta** [comment]
> If you are using VSCode, try running through Gradle.
> 
> I face Exceptions when I run through `Launcher.java` but works through `run` in Gradle.

Ayyy thanks, it worked!  
It gave an error when running `Launcher.java` via VSCode, but it did when i did it via commandline `./gradlew run`.
