### ISSUE TITLE
Cannot run with GUI - Unable to construct Application instance: class willy.WillyApp

### ISSUE THREAD

**Issue by WesleyBLDC** [nus-cs2103-AY2223S2/forum#183]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

I have tried running it on IntelliJ and VSCode. My previous branches were working, when I initially did the GUI it was working but suddenly when I tried to test now it is not working. Even after rolling back to previous branches/commits, it is giving me this same error. Im not sure if its related to my java pathway issue as I randomly chose someone's project and tried to run it and it works (so it does not seem like it is my machine).

also, someone had a similar issue: https://github.com/nus-cs2103-AY2223S2/forum/issues/122
but it did not work for me. 

here is link to my repo: https://github.com/WesleyBLDC/ip/tree/master/src/main/java/willy

wesley@Wesleys-MacBook-Air ip %  cd /Users/wesley/Documents/GitHub/ip ; /usr/bin/env /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/java @/var/folders/wc/sdprkyqd26g3f8h16_j4y4940000gn/T/cp_4yagd2nysv1kneeg9cmywxdjv.argfile willy.L
auncher 
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class willy.WillyApp
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:891)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodException: willy.WillyApp.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3349)
        at java.base/java.lang.Class.getConstructor(Class.java:2151)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by WesleyBLDC** [comment]
Hmm was able to make it work after changing a small thing and running it on intellij...

**Comment by francisyzy** [comment]
Relevant xkcd
![xkcd](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

but no I don’t face this issue. would be better to write down how u solve it so that incase others face this issue, the solution would be there
